# Generated by Django 4.2.13 on 2024-07-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_delet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='is_delet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_classes',
            field=models.IntegerField(default=0),
        ),
    ]
