# Generated by Django 4.2.13 on 2024-07-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_class_is_delet_subject_code_subject_is_delet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='is_delet',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='is_delet',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='is_delet',
            new_name='is_deleted',
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.faculty'),
        ),
    ]
