# Generated by Django 4.2.13 on 2024-07-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('academics', '0003_rename_is_delet_class_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(to='students.student'),
        ),
    ]
