# Generated by Django 4.2.13 on 2024-07-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_class_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='level',
        ),
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
    ]
