# Generated by Django 4.2.13 on 2024-07-24 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('attendance', '0002_attendance_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='teacher.teacher'),
            preserve_default=False,
        ),
    ]
