# Generated by Django 4.2.14 on 2024-08-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_department_name_alter_faculty_name'),
        ('attendance', '0004_alter_qrcode_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject'),
        ),
    ]
