# Generated by Django 4.2.14 on 2024-08-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_qrcode_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='course',
            new_name='subject',
        ),
    ]
