# Generated by Django 4.2.13 on 2024-07-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_remove_class_level_remove_class_students'),
        ('students', '0003_remove_student_subjects_student_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='additional_subjects',
            field=models.ManyToManyField(blank=True, related_name='additional_students', to='academics.subject'),
        ),
    ]
